theme: jekyll-theme-minimal
title: Uindow
logo: /img/256.png
description: Modern, community-driven web automation
google_analytics:
copyright_url: https://uindow.com/?ref=uindow.github.io
show_downloads: true
github:
    repository_nwo: "uindow/uindow"
    repository_url: https://github.com/uindow/uindow/
    repository_notice: https://github.com/uindow/uindow/blob/main/dist/NOTICE.md
    releases_url: https://github.com/uindow/uindow/releases/latest/
